name: livestream_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  
  apivideo_live_stream: ^1.2.0 
  permission_handler: ^11.4.0
  video_player: ^2.9.3
  chewie: ^1.10.0


  flutter:
    sdk: flutter
  rtmp_broadcaster: ^2.3.4
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
